/**
 * Table DDL for provisioning-job PGlite suites, mirroring the Drizzle schemas
 * their service flows read and write. Plain statements avoid drizzle-kit's
 * silent `process.exit(1)` on internal errors, which otherwise kills a
 * multi-file Bun test process (#15943). Every selected Drizzle column must
 * exist here so schema drift fails loudly; foreign keys are omitted because
 * these suites exercise service invariants rather than referential constraints.
 */

export const PROVISIONING_JOB_TEST_TABLES: readonly string[] = [
  `CREATE TABLE IF NOT EXISTS "organizations" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "name" text NOT NULL,
  "slug" text NOT NULL,
  "credit_balance" numeric(12,6) NOT NULL DEFAULT 0.000000,
  "balance_revision" bigint NOT NULL DEFAULT 0,
  "balance_decrease_revision" bigint NOT NULL DEFAULT 0,
  "auto_top_up_covered_balance_decrease_revision" bigint,
  "settings" jsonb DEFAULT '{}'::jsonb,
  "stripe_customer_id" text,
  "billing_email" text,
  "stripe_payment_method_id" text,
  "stripe_default_payment_method" text,
  "auto_top_up_enabled" boolean DEFAULT false,
  "auto_top_up_threshold" numeric(10,2),
  "auto_top_up_amount" numeric(10,2),
  "pay_as_you_go_from_earnings" boolean NOT NULL DEFAULT true,
  "steward_tenant_id" text,
  "steward_tenant_api_key" text,
  "account_lifecycle_state" text NOT NULL DEFAULT 'active',
  "account_lifecycle_revision" bigint NOT NULL DEFAULT 0,
  "account_deletion_request_id" uuid,
  "paid_work_fenced_at" timestamp,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
)`,
  `CREATE TABLE IF NOT EXISTS "users" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "email" text,
  "email_verified" boolean DEFAULT false,
  "wallet_address" text,
  "wallet_chain_type" text,
  "wallet_verified" boolean NOT NULL DEFAULT false,
  "name" text,
  "avatar" text,
  "organization_id" uuid,
  "role" text NOT NULL DEFAULT 'member'::text,
  "steward_user_id" text NOT NULL,
  "telegram_id" text,
  "telegram_username" text,
  "telegram_first_name" text,
  "telegram_photo_url" text,
  "discord_id" text,
  "discord_username" text,
  "discord_global_name" text,
  "discord_avatar_url" text,
  "whatsapp_id" text,
  "whatsapp_name" text,
  "phone_number" text,
  "phone_verified" boolean DEFAULT false,
  "is_anonymous" boolean NOT NULL DEFAULT false,
  "anonymous_session_id" text,
  "expires_at" timestamp,
  "nickname" text,
  "work_function" text,
  "preferences" text,
  "email_notifications" boolean DEFAULT true,
  "response_notifications" boolean DEFAULT true,
  "account_lifecycle_state" text NOT NULL DEFAULT 'active',
  "account_lifecycle_revision" bigint NOT NULL DEFAULT 0,
  "account_deletion_request_id" uuid,
  "auth_fenced_at" timestamp,
  "is_active" boolean NOT NULL DEFAULT true,
  "email_ciphertext" text,
  "email_nonce" text,
  "email_auth_tag" text,
  "email_kms_key_id" text,
  "email_kms_key_version" integer,
  "email_blind_index" text,
  "phone_ciphertext" text,
  "phone_nonce" text,
  "phone_auth_tag" text,
  "phone_kms_key_id" text,
  "phone_kms_key_version" integer,
  "phone_blind_index" text,
  "wallet_address_ciphertext" text,
  "wallet_address_nonce" text,
  "wallet_address_auth_tag" text,
  "wallet_address_kms_key_id" text,
  "wallet_address_kms_key_version" integer,
  "wallet_address_blind_index" text,
  "telegram_id_ciphertext" text,
  "telegram_id_nonce" text,
  "telegram_id_auth_tag" text,
  "telegram_id_kms_key_id" text,
  "telegram_id_kms_key_version" integer,
  "discord_id_ciphertext" text,
  "discord_id_nonce" text,
  "discord_id_auth_tag" text,
  "discord_id_kms_key_id" text,
  "discord_id_kms_key_version" integer,
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now(),
  "deleted_at" timestamp,
  PRIMARY KEY ("id")
)`,
  `CREATE TABLE IF NOT EXISTS "personal_account_convergences" (
  "token" text NOT NULL,
  "source_user_id" uuid NOT NULL,
  "source_organization_id" uuid NOT NULL,
  "source_agent_id" text NOT NULL,
  "target_user_id" uuid NOT NULL,
  "target_organization_id" uuid NOT NULL,
  "target_agent_id" text NOT NULL,
  "phone_number" text NOT NULL,
  "telegram_id" text NOT NULL,
  "steward_user_id" text NOT NULL,
  "status" text NOT NULL DEFAULT 'pending_alias',
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("token")
)`,
  `CREATE TABLE IF NOT EXISTS "user_characters" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "organization_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "name" text NOT NULL,
  "username" text,
  "system" text,
  "bio" jsonb NOT NULL,
  "message_examples" jsonb DEFAULT '[]'::jsonb,
  "post_examples" jsonb DEFAULT '[]'::jsonb,
  "topics" jsonb DEFAULT '[]'::jsonb,
  "adjectives" jsonb DEFAULT '[]'::jsonb,
  "knowledge" jsonb DEFAULT '[]'::jsonb,
  "plugins" jsonb DEFAULT '[]'::jsonb,
  "settings" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "secrets" jsonb DEFAULT '{}'::jsonb,
  "style" jsonb DEFAULT '{}'::jsonb,
  "character_data" jsonb NOT NULL,
  "is_template" boolean NOT NULL DEFAULT false,
  "is_public" boolean NOT NULL DEFAULT false,
  "avatar_url" text,
  "category" text,
  "tags" jsonb DEFAULT '[]'::jsonb,
  "featured" boolean NOT NULL DEFAULT false,
  "view_count" integer NOT NULL DEFAULT 0,
  "interaction_count" integer NOT NULL DEFAULT 0,
  "popularity_score" integer NOT NULL DEFAULT 0,
  "source" text NOT NULL DEFAULT 'cloud'::text,
  "token_address" text,
  "token_chain" text,
  "token_name" text,
  "token_ticker" text,
  "erc8004_registered" boolean NOT NULL DEFAULT false,
  "erc8004_network" text,
  "erc8004_agent_id" integer,
  "erc8004_agent_uri" text,
  "erc8004_tx_hash" text,
  "erc8004_registered_at" timestamp,
  "monetization_enabled" boolean NOT NULL DEFAULT false,
  "inference_markup_percentage" numeric(7,2) NOT NULL DEFAULT 0.00,
  "payout_wallet_address" text,
  "total_inference_requests" integer NOT NULL DEFAULT 0,
  "total_creator_earnings" numeric(12,4) NOT NULL DEFAULT 0.0000,
  "total_platform_revenue" numeric(12,4) NOT NULL DEFAULT 0.0000,
  "a2a_enabled" boolean NOT NULL DEFAULT true,
  "mcp_enabled" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
)`,
  `CREATE TABLE IF NOT EXISTS "agent_sandboxes" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "organization_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "character_id" uuid,
  "sandbox_id" text,
  "status" text NOT NULL DEFAULT 'pending'::text,
  "lifecycle_job_id" uuid,
  "lifecycle_execution_generation" uuid,
  "deletion_attempt_id" uuid,
  "deletion_started_at" timestamptz,
  "deletion_previous_status" text,
  "deletion_previous_billing_status" text,
  "deletion_previous_shutdown_warning_sent_at" timestamptz,
  "deletion_previous_scheduled_shutdown_at" timestamptz,
  "pre_delete_capture_waiver_attempt_id" uuid,
  "pre_delete_capture_waiver_environment_revision" integer,
  "pre_delete_capture_waiver_sandbox_id" text,
  "pre_delete_capture_waiver_bridge_url" text,
  "deletion_allocation_counted" boolean,
  "execution_tier" text NOT NULL DEFAULT 'shared'::text,
  "bridge_url" text,
  "health_url" text,
  "agent_name" text,
  "agent_config" jsonb,
  "database_uri" text,
  "database_status" text NOT NULL DEFAULT 'none'::text,
  "database_error" text,
  "snapshot_id" text,
  "last_backup_at" timestamptz,
  "last_backup_attempt_at" timestamptz,
  "backup_unsupported_reason" text,
  "last_heartbeat_at" timestamptz,
  "error_message" text,
  "error_count" integer NOT NULL DEFAULT 0,
  "environment_vars" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "environment_revision" integer NOT NULL DEFAULT 0,
  "lifecycle_revision" bigint NOT NULL DEFAULT 0,
  "node_id" text,
  "container_name" text,
  "bridge_port" integer,
  "web_ui_port" integer,
  "headscale_ip" text,
  "docker_image" text,
  "image_digest" text,
  "previous_image_digest" text,
  "previous_docker_image" text,
  "billing_status" text NOT NULL DEFAULT 'active'::text,
  "last_billed_at" timestamptz,
  "hourly_rate" numeric(10,4) DEFAULT 0.0100,
  "total_billed" numeric(10,2) NOT NULL DEFAULT 0.00,
  "shutdown_warning_sent_at" timestamptz,
  "scheduled_shutdown_at" timestamptz,
  "pool_status" text,
  "pool_ready_at" timestamptz,
  "claimed_at" timestamptz,
  "warm_claim_credential_state" text,
  "warm_claim_source_pool_id" uuid,
  "warm_claim_key_fingerprint" text,
  "warm_claim_attested_at" timestamptz,
  "warm_claim_attested_environment_revision" integer,
  "warm_claim_cleanup_completed_at" timestamptz,
  "replacement_cleanup_sandbox_id" text,
  "replacement_cleanup_node_id" text,
  "replacement_cleanup_container_name" text,
  "replacement_cleanup_attempt_id" uuid,
  "replacement_cleanup_container_id" text,
  "replacement_cleanup_vpn_node_id" text,
  "replacement_cleanup_vpn_node_name" text,
  "replacement_cleanup_preserved_vpn_node_id" text,
  "replacement_cleanup_vpn_registration_started_at" timestamptz,
  "replacement_cleanup_allocation_counted" boolean,
  "replacement_cleanup_created_at" timestamptz,
  "activation_generation" uuid,
  "activation_lifecycle_revision" bigint,
  "activation_phase" text,
  "activation_receipt_hash" text,
  "activation_container_id" text,
  "activation_node_id" text,
  "activation_image_digest" text,
  "activation_boot_id" uuid,
  "activation_authority_published_at" timestamptz,
  "activation_dispatched_at" timestamptz,
  "activation_completed_at" timestamptz,
  "activation_previous_generation" uuid,
  "activation_purpose" text,
  "activation_backup_id" uuid,
  "activation_backup_hash" text,
  "activation_receipt" jsonb,
  "activation_token_hash" text,
  "activation_token_ciphertext" text,
  "activation_funding_revision" bigint,
  "activation_consent_lifecycle_revision" bigint,
  "activation_consent_head_backup_id" uuid,
  "activation_consent_head_backup_hash" text,
  "next_backup_at" timestamptz,
  "backup_schedule_operation_id" uuid,
  "backup_schedule_retry_at" timestamptz,
  "backup_schedule_claim_owner" text,
  "backup_schedule_claim_generation" uuid,
  "backup_schedule_claim_expires_at" timestamptz,
  "backup_schedule_attempts" integer NOT NULL DEFAULT 0,
  "backup_schedule_last_error_code" text,
  "backup_schedule_last_protected_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "deleted_at" timestamptz,
  PRIMARY KEY ("id")
)`,
  `CREATE INDEX IF NOT EXISTS "agent_sandboxes_activation_generation_idx"
  ON "agent_sandboxes" ("activation_generation")
  WHERE "activation_generation" IS NOT NULL`,
  `CREATE TABLE IF NOT EXISTS "personal_dedicated_upgrade_authorities" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "organization_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "source_agent_id" text NOT NULL,
  "dedicated_agent_id" uuid NOT NULL,
  "schema_version" integer NOT NULL DEFAULT 1,
  "bound_at" timestamptz NOT NULL DEFAULT now(),
  "cutover_token" text,
  "shared_message_count" integer,
  "shared_scheduled_task_count" integer,
  "shared_todo_count" integer,
  "shared_todo_mutation_count" integer,
  "shared_todo_digest" text,
  "cutover_activated_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "personal_dedicated_upgrade_authorities_source_unique"
    UNIQUE ("organization_id", "user_id", "source_agent_id"),
  CONSTRAINT "personal_dedicated_upgrade_authorities_target_unique"
    UNIQUE ("dedicated_agent_id"),
  CONSTRAINT "personal_dedicated_upgrade_authorities_organization_id_fk"
    FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE,
  CONSTRAINT "personal_dedicated_upgrade_authorities_user_id_fk"
    FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE
)`,
  `CREATE TABLE IF NOT EXISTS "personal_dedicated_adoption_selections" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "organization_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "source_agent_id" text NOT NULL,
  "dedicated_agent_id" uuid NOT NULL,
  "selected_by_user_id" uuid,
  "selection_reason" text NOT NULL,
  "state_disposition" text NOT NULL,
  "activation_kind" text NOT NULL,
  "activation_backup_id" uuid,
  "activation_backup_hash" text,
  "activation_backup_chain" jsonb,
  "restore_fence_hash" text,
  "restore_fence_started_at" timestamptz,
  "inventory_fingerprint" text NOT NULL,
  "candidate_count" integer NOT NULL,
  "schema_version" integer NOT NULL DEFAULT 1,
  "selected_at" timestamptz NOT NULL DEFAULT now(),
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "personal_dedicated_adoption_selections_source_unique"
    UNIQUE ("organization_id", "user_id", "source_agent_id"),
  CONSTRAINT "personal_dedicated_adoption_selections_target_unique"
    UNIQUE ("dedicated_agent_id"),
  CONSTRAINT "personal_dedicated_adoption_selections_organization_id_fk"
    FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE,
  CONSTRAINT "personal_dedicated_adoption_selections_user_id_fk"
    FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE,
  CONSTRAINT "personal_dedicated_adoption_selections_selected_by_user_id_fk"
    FOREIGN KEY ("selected_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL,
  CONSTRAINT "personal_dedicated_adoption_selections_activation_check"
    CHECK (("activation_kind" = 'fresh_boot' AND "activation_backup_id" IS NULL
        AND "activation_backup_hash" IS NULL AND "activation_backup_chain" IS NULL)
      OR ("activation_kind" = 'legacy_backup'
        AND "activation_backup_id" IS NOT NULL
        AND "activation_backup_hash" ~ '^[a-f0-9]{64}$'
        AND jsonb_typeof("activation_backup_chain") = 'array'
        AND jsonb_array_length("activation_backup_chain") > 0)
      OR ("activation_kind" = 'catalog_restore_required'
        AND "activation_backup_id" IS NOT NULL
        AND "activation_backup_hash" ~ '^[a-f0-9]{64}$'
        AND "activation_backup_chain" IS NULL)),
  CONSTRAINT "personal_dedicated_adoption_selections_restore_fence_check"
    CHECK (("restore_fence_hash" IS NULL AND "restore_fence_started_at" IS NULL)
      OR ("restore_fence_hash" ~ '^[a-f0-9]{64}$'
        AND "restore_fence_started_at" IS NOT NULL))
)`,
  `CREATE TABLE IF NOT EXISTS "agent_sandbox_backups" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "sandbox_record_id" uuid,
  "snapshot_type" text NOT NULL,
  "state_data" jsonb NOT NULL,
  "state_data_storage" text NOT NULL DEFAULT 'inline'::text,
  "state_data_key" text,
  "size_bytes" bigint,
  "backup_kind" text NOT NULL DEFAULT 'full'::text,
  "parent_backup_id" uuid,
  "base_backup_id" uuid,
  "content_hash" text,
  "verification_status" text,
  "verified_at" timestamptz,
  "verification_error" text,
  "backup_operation_id" uuid,
  "catalog_version" integer,
  "catalog_state" text,
  "catalog_resume_state" text,
  "catalog_payload_digest" text,
  "catalog_revision" bigint NOT NULL DEFAULT 0,
  "catalog_organization_id" uuid,
  "catalog_agent_id" uuid,
  "lifecycle_generation" uuid,
  "lifecycle_revision" numeric,
  "source_provider" text,
  "source_node_record_id" uuid,
  "source_node_id" text,
  "source_node_incarnation" uuid,
  "source_provider_server_id" text,
  "source_provider_handle" text,
  "source_container_id" text,
  "manifest_format" text,
  "manifest_version" integer,
  "manifest_digest" text,
  "manifest_canonical_draft" text,
  "manifest_object_count" integer,
  "object_inventory_digest" text,
  "backup_image_digest" text,
  "database_schema_version" text,
  "plugin_set_digest" text,
  "watermark_digest" text,
  "raw_size_bytes" bigint,
  "compressed_size_bytes" bigint,
  "encrypted_size_bytes" bigint,
  "backup_kms_key_id" text,
  "backup_kms_key_version" bigint,
  "wrapped_dek_ref" text,
  "wrapped_dek_ciphertext_base64" text,
  "wrapped_dek_sha256" text,
  "wrapped_dek_size_bytes" integer,
  "wrapped_dek_receipt_digest" text,
  "operation_key_bundle_generation_id" uuid,
  "operation_key_bundle_format" text,
  "operation_key_bundle_ref" text,
  "operation_key_bundle_ciphertext_base64" text,
  "operation_key_bundle_sha256" text,
  "operation_key_bundle_size_bytes" integer,
  "operation_key_bundle_context" text,
  "operation_key_bundle_context_derivation" text,
  "operation_key_bundle_local_receipt_derivation" text,
  "operation_key_bundle_local_receipt_digest" text,
  "vault_key_generation_id" uuid,
  "vault_key_authority_receipt_digest" text,
  "catalog_attempts" integer NOT NULL DEFAULT 0,
  "catalog_lease_owner" text,
  "catalog_lease_generation" uuid,
  "catalog_lease_expires_at" timestamptz,
  "catalog_next_attempt_at" timestamptz,
  "catalog_last_error_code" text,
  "catalog_last_error" text,
  "retention_reason" text,
  "retention_until" timestamptz,
  "primary_verified_at" timestamptz,
  "secondary_verified_at" timestamptz,
  "restore_verified_at" timestamptz,
  "restore_receipt_digest" text,
  "restore_generation" bigint,
  "catalog_delete_receipt_digest" text,
  "catalog_deleted_at" timestamptz,
  "catalog_updated_at" timestamptz,
  "recovery_organization_id" uuid,
  "recovery_agent_id" uuid,
  "recovery_deletion_attempt_id" uuid,
  "recovery_expires_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
)`,
  `CREATE OR REPLACE FUNCTION guard_personal_dedicated_restore_backup_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  affected_agent_id uuid;
BEGIN
  FOR affected_agent_id IN
    SELECT DISTINCT candidate
    FROM unnest(ARRAY[
      CASE WHEN TG_OP <> 'INSERT' THEN OLD."sandbox_record_id" ELSE NULL END,
      CASE WHEN TG_OP <> 'DELETE' THEN NEW."sandbox_record_id" ELSE NULL END
    ]::uuid[]) AS candidate
    WHERE candidate IS NOT NULL
    ORDER BY candidate
  LOOP
    PERFORM 1 FROM "agent_sandboxes" WHERE "id" = affected_agent_id FOR KEY SHARE;
    IF EXISTS (
      SELECT 1 FROM "personal_dedicated_adoption_selections"
      WHERE "dedicated_agent_id" = affected_agent_id
        AND "restore_fence_hash" IS NOT NULL
    ) THEN
      RAISE EXCEPTION 'reviewed restore authority is fenced for agent %', affected_agent_id
        USING ERRCODE = '55000';
    END IF;
  END LOOP;
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END;
$$`,
  `DROP TRIGGER IF EXISTS "agent_sandbox_backups_reviewed_restore_fence"
ON "agent_sandbox_backups"`,
  `CREATE TRIGGER "agent_sandbox_backups_reviewed_restore_fence"
BEFORE INSERT OR UPDATE OR DELETE ON "agent_sandbox_backups"
FOR EACH ROW EXECUTE FUNCTION "guard_personal_dedicated_restore_backup_mutation"()`,
  `CREATE OR REPLACE FUNCTION advance_agent_sandbox_lifecycle_revision()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.lifecycle_revision := OLD.lifecycle_revision + 1;
  RETURN NEW;
END;
$$`,
  `DROP TRIGGER IF EXISTS agent_sandboxes_lifecycle_revision_trigger ON "agent_sandboxes"`,
  `CREATE TRIGGER agent_sandboxes_lifecycle_revision_trigger
BEFORE UPDATE ON "agent_sandboxes"
FOR EACH ROW
WHEN (
  to_jsonb(OLD) - ARRAY[
    'billing_status',
    'last_billed_at',
    'hourly_rate',
    'total_billed',
    'shutdown_warning_sent_at',
    'scheduled_shutdown_at',
    'updated_at'
  ]::text[]
  IS DISTINCT FROM
  to_jsonb(NEW) - ARRAY[
    'billing_status',
    'last_billed_at',
    'hourly_rate',
    'total_billed',
    'shutdown_warning_sent_at',
    'scheduled_shutdown_at',
    'updated_at'
  ]::text[]
)
EXECUTE FUNCTION advance_agent_sandbox_lifecycle_revision()`,
  `CREATE TABLE IF NOT EXISTS "api_keys" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "name" text NOT NULL,
  "description" text,
  "key_hash" text NOT NULL,
  "key_prefix" text NOT NULL,
  "key_ciphertext" text,
  "key_nonce" text,
  "key_auth_tag" text,
  "key_kms_key_id" text,
  "key_kms_key_version" integer,
  "organization_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "source_app_id" uuid,
  "rate_limit" integer NOT NULL DEFAULT 1000,
  "is_active" boolean NOT NULL DEFAULT true,
  "usage_count" integer NOT NULL DEFAULT 0,
  "expires_at" timestamp,
  "last_used_at" timestamp,
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now(),
  "deleted_at" timestamp,
  PRIMARY KEY ("id")
)`,
  `CREATE TABLE IF NOT EXISTS "jobs" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "type" text NOT NULL,
  "status" text NOT NULL DEFAULT 'pending'::text,
  "data" jsonb NOT NULL,
  "data_storage" text NOT NULL DEFAULT 'inline'::text,
  "data_key" text,
  "agent_id" text,
  "character_id" text,
  "result" jsonb,
  "result_storage" text NOT NULL DEFAULT 'inline'::text,
  "result_key" text,
  "error" text,
  "error_storage" text NOT NULL DEFAULT 'inline'::text,
  "error_key" text,
  "attempts" integer NOT NULL DEFAULT 0,
  "max_attempts" integer NOT NULL DEFAULT 3,
  "execution_interruptions" integer NOT NULL DEFAULT 0,
  "retryable_requeues" integer NOT NULL DEFAULT 0,
  "organization_id" uuid NOT NULL,
  "user_id" uuid,
  "api_key_id" uuid,
  "generation_id" uuid,
  "webhook_url" text,
  "webhook_status" text,
  "estimated_completion_at" timestamp,
  "scheduled_for" timestamp NOT NULL DEFAULT now(),
  "started_at" timestamp,
  "execution_generation" uuid,
  "execution_quiesced_at" timestamp,
  "completed_at" timestamp,
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
)`,
  `CREATE TABLE IF NOT EXISTS "agent_compute_stop_intents" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "organization_id" uuid NOT NULL,
  "agent_id" uuid NOT NULL,
  "lifecycle_revision" bigint NOT NULL,
  "authorization" text NOT NULL DEFAULT 'billing_request',
  "retained_backup_billing" boolean NOT NULL DEFAULT false,
  "retained_backup_rate_per_hour" numeric(18,6),
  "status" text NOT NULL DEFAULT 'pending',
  "job_id" uuid REFERENCES "jobs"("id") ON DELETE SET NULL,
  "attempts" integer NOT NULL DEFAULT 0,
  "last_error" text,
  "next_attempt_at" timestamptz NOT NULL DEFAULT now(),
  "provider_started_at" timestamptz,
  "provider_confirmed_at" timestamptz,
  "superseded_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "agent_compute_stop_intents_status_check" CHECK (
    "status" IN ('pending', 'dispatching', 'retry', 'terminal_attention', 'provider_confirmed', 'superseded')
  ),
  CONSTRAINT "agent_compute_stop_intents_authorization_check" CHECK (
    "authorization" IN ('billing_request', 'user_request')
  ),
  CONSTRAINT "agent_compute_stop_intents_retained_backup_billing_check" CHECK (
    ("retained_backup_billing" = true AND "retained_backup_rate_per_hour" > 0)
    OR ("retained_backup_billing" = false AND "retained_backup_rate_per_hour" IS NULL)
  )
)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "agent_compute_stop_intents_active_unique"
  ON "agent_compute_stop_intents" ("organization_id", "agent_id")
  WHERE "status" IN ('pending', 'dispatching', 'retry', 'terminal_attention')`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "agent_compute_stop_intents_user_request_unique"
  ON "agent_compute_stop_intents" ("organization_id", "agent_id", "lifecycle_revision")
  WHERE "authorization" = 'user_request'`,
  `CREATE INDEX IF NOT EXISTS "agent_compute_stop_intents_recovery_idx"
  ON "agent_compute_stop_intents" ("status", "next_attempt_at")
  WHERE "status" IN ('pending', 'retry', 'terminal_attention')`,
  `CREATE TABLE IF NOT EXISTS "credit_transactions" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "organization_id" uuid NOT NULL,
  "user_id" uuid,
  "amount" numeric(16,6) NOT NULL,
  "type" text NOT NULL,
  "description" text,
  "metadata" jsonb,
  "stripe_payment_intent_id" text,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "settled_at" timestamptz,
  CONSTRAINT "credit_transactions_id_organization_unique" UNIQUE ("id", "organization_id")
)`,
  `CREATE TABLE IF NOT EXISTS "agent_billing_records" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "organization_id" uuid NOT NULL,
  "sandbox_id" uuid NOT NULL,
  "sandbox_status" text NOT NULL,
  "billing_period_start" timestamptz NOT NULL,
  "billing_period_end" timestamptz NOT NULL,
  "hourly_rate" numeric(16,6) NOT NULL,
  "amount" numeric(16,6) NOT NULL,
  "rate_segments" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "credit_transaction_id" uuid NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now()
)`,
  `CREATE TABLE IF NOT EXISTS "compute_billing_rate_segments" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "organization_id" uuid NOT NULL,
  "workload_kind" text NOT NULL,
  "workload_id" uuid NOT NULL,
  "lifecycle_revision" bigint NOT NULL,
  "billing_state" text NOT NULL,
  "rate_per_hour" numeric(16,6) NOT NULL,
  "effective_at" timestamptz NOT NULL DEFAULT now(),
  "created_at" timestamptz NOT NULL DEFAULT now()
)`,
  `CREATE TABLE IF NOT EXISTS "job_execution_leases" (
  "job_id" uuid NOT NULL,
  "execution_generation" uuid NOT NULL,
  "owner_id" uuid NOT NULL,
  "expires_at" timestamp NOT NULL,
  "heartbeat_at" timestamp NOT NULL DEFAULT now(),
  "created_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("job_id")
)`,
  `CREATE SCHEMA IF NOT EXISTS "app_scheduling"`,
  `CREATE TABLE IF NOT EXISTS "app_scheduling"."life_scheduled_tasks" (
  "id" text NOT NULL,
  "agent_id" text NOT NULL,
  "kind" text NOT NULL,
  "prompt_instructions" text NOT NULL,
  "context_request_json" text,
  "trigger_json" text NOT NULL,
  "priority" text DEFAULT 'medium' NOT NULL,
  "should_fire_json" text,
  "completion_check_json" text,
  "escalation_json" text,
  "output_json" text,
  "pipeline_json" text,
  "subject_kind" text,
  "subject_id" text,
  "idempotency_key" text,
  "respects_global_pause" boolean DEFAULT true NOT NULL,
  "state_json" text DEFAULT '{}' NOT NULL,
  "source" text DEFAULT 'user_chat' NOT NULL,
  "created_by" text DEFAULT '' NOT NULL,
  "owner_visible" boolean DEFAULT true NOT NULL,
  "metadata_json" text DEFAULT '{}' NOT NULL,
  "execution_profile" text,
  "transfer_token" text,
  "transfer_holder_token" text,
  "transfer_target_agent_id" text,
  "transfer_status" text,
  "version" integer DEFAULT 1 NOT NULL,
  "next_fire_at" timestamptz,
  "created_at" text NOT NULL,
  "updated_at" text NOT NULL
,
  PRIMARY KEY ("agent_id", "id")
)`,
  `CREATE SCHEMA IF NOT EXISTS "todos"`,
  `CREATE TABLE IF NOT EXISTS "todos"."todos" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "agent_id" uuid NOT NULL,
  "entity_id" uuid NOT NULL,
  "room_id" uuid,
  "world_id" uuid,
  "content" text NOT NULL,
  "active_form" text NOT NULL,
  "status" text NOT NULL,
  "parent_todo_id" uuid,
  "parent_trajectory_step_id" text,
  "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL,
  "completed_at" timestamp
)`,
  `CREATE INDEX IF NOT EXISTS "idx_todos_entity_status"
  ON "todos"."todos" ("entity_id", "status")`,
  `CREATE INDEX IF NOT EXISTS "idx_todos_agent_entity"
  ON "todos"."todos" ("agent_id", "entity_id")`,
  `CREATE INDEX IF NOT EXISTS "idx_todos_room"
  ON "todos"."todos" ("room_id")`,
  `CREATE TABLE IF NOT EXISTS "todos"."todo_mutations" (
  "mutation_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "agent_id" uuid NOT NULL,
  "entity_id" uuid NOT NULL,
  "idempotency_key" text NOT NULL,
  "request_digest" text NOT NULL,
  "operation" text NOT NULL,
  "applied" boolean NOT NULL,
  "result_json" jsonb NOT NULL,
  "committed_at" timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT "todo_mutations_agent_entity_idempotency_key_unique"
    UNIQUE ("agent_id", "entity_id", "idempotency_key")
)`,
  `CREATE INDEX IF NOT EXISTS "idx_todo_mutations_scope_commit"
  ON "todos"."todo_mutations"
  ("agent_id", "entity_id", "committed_at", "mutation_id")`,
];

export const TIER_UPGRADE_TEST_TABLES = PROVISIONING_JOB_TEST_TABLES;
